# Generated by Django 5.1.6 on 2025-03-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encodings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
