# Generated by Django 5.1.6 on 2025-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_face_encodings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_encodings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
