# Generated by Django 5.1.6 on 2025-03-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_face_encodings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_encodings',
        ),
    ]
