# Generated by Django 5.1.6 on 2025-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10, unique=True)),
                ('route', models.TextField()),
                ('current_latitude', models.FloatField(default=0.0)),
                ('current_longitude', models.FloatField(default=0.0)),
            ],
        ),
    ]
