# Generated by Django 5.1.6 on 2025-03-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='current_longitude',
        ),
        migrations.AddField(
            model_name='bus',
            name='current_stop',
            field=models.CharField(default='Not Assigned', max_length=255),
        ),
    ]
