# Generated by Django 5.1.6 on 2025-03-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_busdriver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusDriver',
        ),
    ]
