# Generated by Django 5.1.6 on 2025-03-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_delete_busdriver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
